version: "3"
services:
    folder_autobackup:
        build:
            context: ./
        image: folder_autobkp:latest
        container_name: ${CONTAINER_NAME}
        labels:
            - traefik.enable=false
        env_file: .env
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${DATA_LOCATION}:/opt/data
        command: crond -f -d 8
        restart: always
