#!/bin/sh

BACKUP_FOLDER=/opt/backup
DATA_FOLDER=/opt/data
NOW=$(date +'%Y-%m-%dT%H%M%SZ')

GZIP=$(which gzip)
TAR=$(which tar)
LS=$(which ls)
GREP=$(which grep)
TAIL=$(which tail)
XARGS=$(which xargs)
RM=$(which rm)

TAIL_SIZE=$(($BKP_HIST_SIZE+2))

[ ! -d $BACKUP_FOLDER ] && mkdir --parents $BACKUP_FOLDER

FILE=$BACKUP_FOLDER/backup-data-$DATA_NAME-$NOW.tar.gz

$TAR -zcvf $FILE $DATA_FOLDER/

$LS -tp $BACKUP_FOLDER/ | $GREP -v '/$' | $GREP "backup-data-$DATA_NAME" |$TAIL -n +$TAIL_SIZE | $XARGS -I {} $RM -- $BACKUP_FOLDER/{}
cp $FILE $BACKUP_FOLDER/backup-data-$DATA_NAME.tar.gz
